### ISSUE TITLE
Incorrect thumbnail generation with `getThumbnailSet`

### ISSUE THREAD

**Issue by glyg** [ome/omero-py#209]
Hi,

I hope it is the right repository to put this.
I use the thumbnail service API to generate html images. The generated thumbnails do not seem correct except for the 48pix size. With other sizes, the result does not look like the original image, and is not always the same when changing image size.

Bellow `conn` is a `BlitzGateway` connection to the database

```py
ths = conn.getThumbnailSet([image.id,], max_size=48)[image.id]
tag_start = (
    '<img style="width: 200px; max-height: 200px" src="data:image/png;base64,'
)
thumb = base64.b64encode(ths).decode("utf-8")
thumb_html = f'{tag_start}{thumb}">'
```

Here is the image in the iviewer:
![Capture d’écran de 2020-04-28 17-33-29](https://user-images.githubusercontent.com/1426279/80507456-28fcef80-8977-11ea-9637-6127767a114e.png)

Here are the thumbnails generated for two sizes. The 48px one is correct (but I understand it was cached at import time.
![Capture d’écran de 2020-04-28 17-34-33](https://user-images.githubusercontent.com/1426279/80507465-2ac6b300-8977-11ea-90c4-ce7a41a85e92.png)

I'm using omero-py 5.6.2 on the client side, the server (still) runs on 5.6.0 - I do not dare update it entirely remotely and cannot access the machine yet.

**Comment by glyg** [comment]
Digging a bit more:
- This seems to work fine when the images belong to the user, but not when I access images only with  `SERVICE_OPTS.setGroup("-1")` 

- The following method works: 
```py
conn.SERVICE_OPTS.setOmeroGroup("-1")
tb = conn.createThumbnailStore()
tb.setPixelsId(16426, conn.SERVICE_OPTS)
thumb = tb.getThumbnailDirect(rint(12), rint(12), conn.SERVICE_OPTS)
```
If `conn.SERVICE_OPTS` is not passed, I get a `ResourceError` or a `nullPointerException`.

I could not find the `ThumbnailStore` definition, so could not go further.

Hope this helps,

Guillaume

**Comment by will-moore** [comment]
Hi Guillaume,

Are you working in a read-only group?
In that case, you cannot create rendering settings (and save thumbnails) on another user's images. If you ask for a thumbnail of a size that has been cached by another user, then you will get that cached thumbnail.

In testing just now, I find that if you ask for a thumbnail using ```conn.getThumbnailSet()``` for another user's image in a read-only group, for a size that hasn't been created yet, you get a ```SecurityViolation "Updating ome.model.display.Thumbnail:Id_1732 not allowed."```.
Do you see the same thing if you choose other sizes?

I wonder if you are seeing rendering settings saved on the image by other users? In iviewer you only see a single"User Setting" (in your screenshot). But what do you see if you go to 
```/webgateway/get_image_rdefs_json/16416/``` (use the correct image ID).

When you ask for the thumbnail "direct" it doesn't try to use (or to cache) the thumbnail.

To use the BlitzGateway to get a thumbnail direct (as in your last example), you can

```
i = conn.getObject('Image', 1798)
t = i.getThumbnail(size=50, direct=True)
```

In case it's useful, this is a handy way to view the thumbnail in the python interactive terminal:
```
from PIL import Image
from io import BytesIO

data = conn.getThumbnailSet([1798], max_size=96)[1798]
Image.open(BytesIO(data)).show()
```

Unfortunately the thumbnail logic is a little complex due to the caching and OMERO permissions, particularly in a read-only group.
A lot depends on who views the image (creates rendering settings) and asks for thumbnails first and the behaviour you're seeing could be due to that history.
Hope some of this is useful,
Regards,

  Will

**Comment by glyg** [comment]
Hi Will,

Thank you for the detailed response and the `i.getThumbnail` method (it will prove cleaner).

I don't think I saw the `SecurityViolation` error you mention. I think it boils down to me trying to bulldoze my way through permission access though :), so I'll be sure to get this straight.

I still think there is a bug somewhere because the getThumbnailSet methods returns seemingly random thumbnails (that is, thumbnails from other images in the base).

I'll investigate a bit more with what you said next week,

Best

Guillaume

**Comment by will-moore** [comment]
Sorry, I didn't realise the incorrect thumbnail was from a different image, I just thought the rendering settings were different.
Is it possible that your binary repository ```Thumbnails/``` directory has got out of sync with your database (e.g. I've had this happen on test systems when I've dropped the DB but not wiped the binary repository)?
I don't know of anything else that would cause you to get incorrect images as thumbnails.
If you have access to the binary repository ```Thumbnails/``` directory, you can query the thumbnails table to get thumbnail IDs for a particular pixels ID and check if the correct thumbnails are in that directory?

 Will.

**Comment by glyg** [comment]
Hi,

I did not do anything to the binary repository but the out of sync hypothesis could be it, as I restored the db from a 4 year old dump. I'll investigate later.

Thanks, I'll close this, as I think it is not really a bug.

**Comment by glyg** [comment]
Just for completeness, doing a clean with `omero admin cleanse` indeed fixed the problem
